### ISSUE TITLE
Installation failed when "bin" directory in "/usr/local/" is missing

### ISSUE THREAD

**Issue by g0blin79** [bmeme/memento#1]
Hi dude!

Tried to install memento in a fresh mac-os-x installation where "bin" directory in "/usr/local/" is missing yet.

Your code in "install.pl" says:

```perl
if (!-f "/usr/local/bin/memento") {
  say "\n>> Creating memento symlink";
  `ln -s $cwd/memento.pl /usr/local/bin/memento`;
}

say "\nMemento installation finished.";
```

The "if" checks if a "memento" file exists into "/usr/local/bin" but, it doesn't check if the path exists!
I don't know Perl as well as you, but I think you should change that in something like this:

```perl
if (!-d "/usr/local/bin") {
   `mkdir -p /usr/local/bin`;
}

if (!-f "/usr/local/bin/memento") {
  say "\n>> Creating memento symlink";
  `ln -s $cwd/memento.pl /usr/local/bin/memento`;
}

say "\nMemento installation finished.";
```

Let me know ;)

**Comment by Fatal-Error** [comment]
bug fixed in development and master branches.
Thx
