### ISSUE TITLE
Command git start failed if configuration is needed

### ISSUE THREAD

**Issue by Mithenks** [bmeme/memento#15]
If I run `memento git start` in a project where memento is not yet configured, the command fails.

The problem seems to occur when configuration is created on the fly with the `git start` command.
If the command is launched right after in the terminal, everything is fine.

Reported error is:
`Can't call method "_get_issue" on an undefined value at /home/mithenks/BMEME/Projects/memento/Memento/Tool/git.pm line 179, <STDIN> line 4.`

See the screenshot for further details:
![Screenshot_20191127_120435](https://user-images.githubusercontent.com/445544/69718540-ea84af80-110e-11ea-86ea-acae3f8e8320.png)

**Comment by Fatal-Error** [comment]
Fixed on #16
