### ISSUE TITLE
Pull source branch when "memento git start"

### ISSUE THREAD

**Issue by g0blin79** [bmeme/memento#2]
Working with Merge Request method could happen that remote source branch (usually integration branch) is updated and I don't really know about that (or I forgot) because the Merge Request was merged previously.

IMHO could be useful that, when I do a `memento git start` command, memento pulls source branch *before* new branch is created starting from it. In this way i can always have local and remote source branch synced and I am sure that my forked branch is ok.

**Comment by Fatal-Error** [comment]
@g0blin79 your feature request has been added into the latest version of the software: v0.9.8

Thx! :)
